name: haskell-book-sandbox
version: 0.1.0.0
github: "marczinusd/haskell-book-sandbox"
license: BSD3
author: "David Marczinus"
maintainer: "marczinus dot david at gmail dot com"
copyright: "2021 David Marczinus"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/marczinusd/haskell-book-sandbox#readme>

dependencies:
  - base >= 4.7 && < 5
library:
  source-dirs: src

executables:
  haskell-book-sandbox-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-book-sandbox

tests:
  haskell-book-sandbox-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -v1
    dependencies:
      - haskell-book-sandbox
      - hspec
      - hspec-core
      - QuickCheck
