name: haskell-sandbox
version: 0.1.0.0
github: "marczinusd/haskell-sandbox"
license: BSD3
author: "David Marczinus"
maintainer: "marczinus dot david at gmail dot com"
copyright: "2021 David Marczinus"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/marczinusd/haskell-sandbox#readme>

dependencies:
  - base >= 4.7 && < 5
library:
  source-dirs: src
  dependencies:
    - containers
    - random
    - transformers

executables:
  haskell-sandbox-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-sandbox

tests:
  haskell-book-test:
    main: Spec.hs
    source-dirs: test/haskell-book
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -v1
    dependencies:
      - haskell-sandbox
      - hspec
      - hspec-core
      - QuickCheck
      - containers
  haskell-course-test:
    main: Spec.hs
    source-dirs: test/haskell-course
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -v1
    dependencies:
      - haskell-sandbox
      - hspec
      - hspec-core
      - QuickCheck
      - containers
  exercism-test:
    main: Spec.hs
    source-dirs: test/exercism
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -v1
    dependencies:
      - haskell-sandbox
      - hspec
      - hspec-core
      - QuickCheck
      - containers
